

#[server]
#headless = true
#runOnSave = true
#fileWatcherType = "poll"

#[database]
MONGODB_URI = "mongodb+srv://202211504:APoiboNwZGFYm9cQ@cluster0.eeyewov.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
